CREATE TABLE IF NOT EXISTS resumes (
  id BIGSERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  content TEXT
);

CREATE TABLE IF NOT EXISTS applications (
  id BIGSERIAL PRIMARY KEY,
  job_id BIGINT NOT NULL REFERENCES jobs(id) ON DELETE CASCADE,
  status VARCHAR(50),
  notes TEXT,
  applied_at TIMESTAMPTZ DEFAULT NOW()
);
